# pytorch_lightning==2.1.0
seed_everything: 123
trainer:
  accelerator: auto
  strategy: auto
  devices:
  - 3
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: 100000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  encoder_pair: clap
  encoder_pair_kwargs:
    enable_fusion: false
    amodel: HTSAT-base
  encoder_pair_ckpt: diffgar/models/pretrained_ckpt/CLAP/music_audioset_epoch_15_esc_90.14.pt
  scheduler_name: cvssp/audioldm2
  scheduler_pred_type: sample
  unet_model_config:
    dim: 1
    in_channels: 512
    out_channels: 512
    channels:
    - 1024
    - 1024
    - 1536
    - 2048
    factors:
    - 2
    - 2
    - 4
    - 4
    items:
    - 1
    - 1
    - 2
    - 2
    attentions:
    - 0
    - 0
    - 1
    - 1
    cross_attentions:
    - 0
    - 0
    - 1
    - 1
    attention_features: 768
    attention_heads: 8
    embedding_features: 768
    use_classifier_free_guidance: true
    embedding_max_length: 77
    resnet_groups: 2
  unet_ckpt: null
  snr_gamma: null
  freeze_encoder_pair: true
  freeze_unet: false
  uncondition: false
  subject_flagging: false
  train_slider_concept: null
  preextracted_latents: true
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.0001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 1.0e-05
      amsgrad: false
      maximize: false
      foreach: null
      capturable: false
      differentiable: false
      fused: null
  scheduler: null
data:
  task: song_describer
  task_kwargs: {}
  return_audio: true
  return_text: true
  concept: null
  target_n_samples: 96000
  target_sr: 48000
  batch_size: 32
  num_workers: 4
  preextracted_features: true
  truncate_preextracted: 64
log: 'true'
log_model: false
ckpt_path: s3://maml-aimcdt/storage/julien/DiffGAR/training
resume_id: null
resume_from_checkpoint: null
project: DiffGAR-LDM
