#!/bin/bash
# This is the entry point that the docker container uses once it's launched on SageMaker
set -eu -o pipefail
FILE=s3://maml-aimcdt/storage/julien/DiffGAR/training_configs/config.yaml

if [ -f $FILE ]; then
  SCRIPT=$(jq -r .entrypoint < $FILE)
  MODULE=$(echo "${SCRIPT%.*}" | tr / .)  # this converts from package/sub/module.py to package.sub.module
  echo "==== ENTRYPOINT SUMMARY     ===="
  echo "Executing script: ${SCRIPT}"
  echo "Executing command: python -m ${MODULE} --config ${FILE} $@"
  echo "==== ENTRYPOINT SUMMARY END ===="
  pip list --format=freeze > pip_list.txt  # save the list of installed packages
  cp -r . /opt/ml/model/src  # copy the source code to a folder that will be uploaded by sagemaker
  python -m "${MODULE}"
else
  echo "==== ENTRYPOINT SUMMARY     ===="
  echo "Config file not found: ${FILE}"
  echo "Quitting"
  echo "==== ENTRYPOINT SUMMARY END ===="
fi