
base_name: diffgar-extract
pull_config: s3://maml-aimcdt/storage/julien/DiffGAR/training_configs/preprocessing_config.yaml
processing_inputs:
  - source: s3://maml-aimcdt/datasets/song-describer/data/audio/
    input_name: audio
    destination: /opt/ml/processing/input
processing_outputs:
  - destination: s3://maml-aimcdt/datasets/song-describer/data/npy/1hz/
    output_name: npy
    source: /opt/ml/processing/output
processor:
  image_uri: 427750820708.dkr.ecr.us-east-1.amazonaws.com/diffgar/training:latest
  instance_count: 1
  instance_type: ml.g5.2xlarge
  volume_size_in_gb: 450
  entrypoint: [python, -m, extract_dataset, --config, s3://maml-aimcdt/storage/julien/DiffGAR/training_configs/preprocessing_config.yaml]
  tags:
    - Key: Project
      Value: maml-diffgar
    - Key: Application-Name
      Value: MAML